spring.datasource.url=jdbc:mysql://localhost:3306/nome_do_banco_de_dados
spring.datasource.username=seu_usuario_do_banco
spring.datasource.password=sua_senha_do_banco
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver